# -*- coding: utf-8 -*-
"""8_puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XcEiuWeu4nidXVvacUWFLfgJf9DpF0jl
"""

def dfs(state, goal, visited, path, cost, limit):

    # Goal test
    if state == goal:
        return path, cost

    # Stop if depth limit reached
    if cost == limit:
        return None, None

    visited.add(state)

    # Position of blank
    blank = state.index(0)

    # Possible moves
    moves = {
        0: [1, 3],
        1: [0, 2, 4],
        2: [1, 5],
        3: [0, 4, 6],
        4: [1, 3, 5, 7],
        5: [2, 4, 8],
        6: [3, 7],
        7: [4, 6, 8],
        8: [5, 7]
    }

    # Generate next states
    for new_position in moves[blank]:

        new_state = list(state)

        # Swap blank
        new_state[blank], new_state[new_position] = \
            new_state[new_position], new_state[blank]

        new_state = tuple(new_state)

        if new_state not in visited:

            result_path, result_cost = dfs(
                new_state,
                goal,
                visited,
                path + [new_state],
                cost + 1,
                limit
            )

            if result_path is not None:
                return result_path, result_cost

    return None, None


# Input
print("Enter initial state:")
initial = tuple(map(int, input().split()))

print("Enter goal state:")
goal = tuple(map(int, input().split()))

# DFS depth limit
limit = 50

visited = set()

path, cost = dfs(initial, goal, visited, [initial], 0, limit)

# Output
if path:
    print("\nSolution found!")
    print("Path Cost:", cost)

    print("\nPath:")
    for state in path:
        print(state)

else:
    print("No solution found.")

print("Deeksha R Naik (1WN24CS086)")