# -*- coding: utf-8 -*-
"""A*_algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I7lFC_2jGazCS0SyVim3kyFxcq-qnEO
"""

import heapq

class PuzzleNode:
    def __init__(self, state, g_cost, h_cost, parent=None):
        self.state = state
        self.g_cost = g_cost
        self.h_cost = h_cost
        self.f_cost = g_cost + h_cost
        self.parent = parent

    def __lt__(self, other):
        return self.f_cost < other.f_cost

def get_manhattan_distance(state, goal_state):
    """Calculates the sum of absolute distances of tiles from their goal positions."""
    distance = 0
    goal_positions = {}
    for r in range(3):
        for c in range(3):
            goal_positions[goal_state[r][c]] = (r, c)

    for r in range(3):
        for c in range(3):
            val = state[r][c]
            if val != 0:
                target_r, target_c = goal_positions[val]
                distance += abs(r - target_r) + abs(c - target_c)
    return distance

def get_neighbors(state):
    """Finds all valid adjacent states by moving the blank tile (0)."""
    neighbors = []
    blank_r, blank_c = 0, 0
    for r in range(3):
        for c in range(3):
            if state[r][c] == 0:
                blank_r, blank_c = r, c
                break

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dr, dc in moves:
        new_r, new_c = blank_r + dr, blank_c + dc
        if 0 <= new_r < 3 and 0 <= new_c < 3:
            new_state = [list(row) for row in state]
            new_state[blank_r][blank_c], new_state[new_r][new_c] = new_state[new_r][new_c], new_state[blank_r][blank_c]
            neighbors.append(tuple(tuple(row) for row in new_state))

    return neighbors

def solve_8_puzzle(initial_state, goal_state):
    """Solves the 8-puzzle problem using A* algorithm."""
    open_list = []
    closed_set = set()

    start_h = get_manhattan_distance(initial_state, goal_state)
    start_node = PuzzleNode(initial_state, 0, start_h)
    heapq.heappush(open_list, start_node)

    while open_list:
        current_node = heapq.heappop(open_list)

        if current_node.state == goal_state:
            path = []
            while current_node:
                path.append(current_node)
                current_node = current_node.parent
            return path[::-1]

        closed_set.add(current_node.state)

        for neighbor_state in get_neighbors(current_node.state):
            if neighbor_state in closed_set:
                continue

            g_cost = current_node.g_cost + 1
            h_cost = get_manhattan_distance(neighbor_state, goal_state)
            neighbor_node = PuzzleNode(neighbor_state, g_cost, h_cost, current_node)
            heapq.heappush(open_list, neighbor_node)

    return None

def print_solution(path):
    """Formats and prints the puzzle path along with g(n), h(n), and f(n)."""
    if not path:
        print("\n[!] No solution found. The puzzle may be unsolvable from this configuration.")
        return

    print(f"\n======================================")
    print(f" Optimal Solution Found in {len(path) - 1} Moves!")
    print(f"======================================\n")
    for index, node in enumerate(path):
        print(f"--- Step {index} ---")
        for row in node.state:
            print(" ".join(str(tile) if tile != 0 else "_" for tile in row))
        print(f"g(n) = {node.g_cost}  (moves from start)")
        print(f"h(n) = {node.h_cost}  (Manhattan distance to goal)")
        print(f"f(n) = {node.f_cost}  (total state cost)")
        print("-" * 25 + "\n")

def get_user_matrix(matrix_name):
    """Prompts the user to input a valid 3x3 grid matrix configuration."""
    print(f"\n--- Enter the configuration for the {matrix_name} ---")
    print("Use numbers 1-8 for tiles, and 0 or '_' for the blank space.")
    print("Separate numbers in a row by spaces (e.g., '1 2 3').")

    while True:
        try:
            grid = []
            for i in range(3):
                row_input = input(f"Enter row {i+1}: ").strip().replace('_', '0')
                row_parsed = [int(x) for x in row_input.split()]
                if len(row_parsed) != 3:
                    raise ValueError("Each row must contain exactly 3 numbers.")
                grid.append(tuple(row_parsed))

            full_matrix = tuple(grid)

            flattened = [item for row in full_matrix for item in row]
            if sorted(flattened) != list(range(9)):
                print("[Error] Invalid configuration! The board must contain numbers from 0 to 8 with no duplicates.")
                continue

            return full_matrix
        except ValueError as e:
            print(f"[Error] Invalid input: {e}. Please re-enter the entire grid matrix.")

if __name__ == "__main__":
    print("==============================================")
    print(" 8-Puzzle Solver using A* Search Algorithm")
    print("==============================================")

    initial_state = get_user_matrix("INITIAL STATE")
    goal_state = get_user_matrix("GOAL STATE")

    print("\n[Thinking] Processing search graph path...")
    solution_path = solve_8_puzzle(initial_state, goal_state)
    print_solution(solution_path)