# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8mo19fuuK_ZJlEAnziANRIq2F3_yDlb
"""

import math

# -----------------------------------
# Initial Board
# 0:O, 1:blank, 2:X
# 3:X, 4:blank, 5:blank
# 6:X, 7:O, 8:O
# -----------------------------------

board = [
    'O', ' ', 'X',
    'X', ' ', ' ',
    'X', 'O', 'O'
]

path_cost = 0


# -----------------------------------
# Display Board
# -----------------------------------

def print_board(b):
    print()
    print(f" {b[0]} | {b[1]} | {b[2]} ")
    print("---|---|---")
    print(f" {b[3]} | {b[4]} | {b[5]} ")
    print("---|---|---")
    print(f" {b[6]} | {b[7]} | {b[8]} ")
    print()


# -----------------------------------
# Check Winner
# -----------------------------------

def is_winner(b, letter):

    winning_conditions = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),

        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),

        (0, 4, 8),
        (2, 4, 6)
    ]

    return any(
        b[i] == b[j] == b[k] == letter
        for i, j, k in winning_conditions
    )


# -----------------------------------
# Check Board Full
# -----------------------------------

def is_board_full(b):
    return ' ' not in b


# -----------------------------------
# Get Empty Positions
# -----------------------------------

def get_empty_cells(b):
    return [i for i, spot in enumerate(b) if spot == ' ']


# -----------------------------------
# Minimax Algorithm
# -----------------------------------

def minimax(b, is_maximizing):

    # AI wins
    if is_winner(b, 'O'):
        return 1

    # Player wins
    if is_winner(b, 'X'):
        return -1

    # Draw
    if is_board_full(b):
        return 0

    # AI's turn
    if is_maximizing:

        best_score = -math.inf

        for cell in get_empty_cells(b):

            b[cell] = 'O'

            score = minimax(b, False)

            b[cell] = ' '

            best_score = max(best_score, score)

        return best_score

    # Player's turn
    else:

        best_score = math.inf

        for cell in get_empty_cells(b):

            b[cell] = 'X'

            score = minimax(b, True)

            b[cell] = ' '

            best_score = min(best_score, score)

        return best_score


# -----------------------------------
# AI Move
# -----------------------------------

def ai_move(b):

    global path_cost

    best_score = -math.inf
    move = None

    for cell in get_empty_cells(b):

        b[cell] = 'O'

        score = minimax(b, False)

        b[cell] = ' '

        if score > best_score:
            best_score = score
            move = cell

    b[move] = 'O'

    path_cost += 1

    print("AI selected position:", move)
    print("Path Cost:", path_cost)


# -----------------------------------
# Player Move
# -----------------------------------

def player_move(b):

    global path_cost

    while True:

        try:

            choice = int(input("Enter position (0-8): "))

            if choice < 0 or choice > 8:
                print("Enter a number between 0 and 8.")
                continue

            if b[choice] != ' ':
                print("That position is already occupied!")
                continue

            b[choice] = 'X'

            path_cost += 1

            print("Path Cost:", path_cost)

            break

        except ValueError:

            print("Invalid input. Enter a number between 0 and 8.")


# -----------------------------------
# Main Program
# -----------------------------------

print("================================")
print("       TIC-TAC-TOE")
print("================================")

print("You are X")
print("AI is O")

print("\nInitial State:")
print_board(board)

print("Initial Path Cost:", path_cost)


# -----------------------------------
# Check if Initial State is Already
# a Winning State
# -----------------------------------

if is_winner(board, 'X'):

    print("X has already won!")
    print("Game Over.")

elif is_winner(board, 'O'):

    print("O has already won!")
    print("Game Over.")

elif is_board_full(board):

    print("It's a tie!")
    print("Game Over.")

else:

    # -----------------------------------
    # Game Loop
    # -----------------------------------

    while True:

        # -------------------------------
        # Player Move
        # -------------------------------

        player_move(board)

        print("\nAfter Player Move:")
        print_board(board)

        # Check X winner immediately
        if is_winner(board, 'X'):

            print("X wins!")
            print("Final Path Cost:", path_cost)
            break

        # Check draw
        if is_board_full(board):

            print("It's a tie!")
            print("Final Path Cost:", path_cost)
            break


        # -------------------------------
        # AI Move
        # -------------------------------

        print("AI's turn...")

        ai_move(board)

        print("\nAfter AI Move:")
        print_board(board)

        # Check O winner immediately
        if is_winner(board, 'O'):

            print("AI (O) wins!")
            print("Final Path Cost:", path_cost)
            break

        # Check draw
        if is_board_full(board):

            print("It's a tie!")
            print("Final Path Cost:", path_cost)
            break